import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "@/context/session";
import { ThemeProvider } from "@/context/themeProvider";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import SibarMenu from "@/app/ui/sibarMenu";
import Header from "@/app/ui/header";
import UserProvider from "@/context/userProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken");
  const refreshToken = cookieStore.get("refreshToken");
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(fontSans.variable, "overflow-hidden")}>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider
            accessToken={accessToken?.value}
            refreshToken={refreshToken?.value}
          >
            <UserProvider>
              <SibarMenu>
                <div className="flex flex-col">
                  <Header />
                  <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
                    {children}
                  </main>
                </div>
              </SibarMenu>
            </UserProvider>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
